### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-kd4lm4h7#1]
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data. Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by coffeendude** [comment]
<img width="1242" alt="Screen Shot 2022-11-23 at 1 32 45 AM" src="https://user-images.githubusercontent.com/109362460/203492897-14c0be3a-69e8-46b8-87a4-342663b9f844.png">

Updated all images with placeholder when content is empty
